name: Push to EC2

on: push

jobs:
  push:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout the file
        uses: actions/checkout@v2

      - name: Deploy to EC2
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{secrets.EC2_PEM }}
          REMOTE_HOST: "ec2-16-170-173-195.eu-north-1.compute.amazonaws.com"
          SOURCE: "./"
          REMOTE_USER: "ubuntu"
          TARGET: "/var/www/html"

      - name: Restart Apache
        uses: appleboy/ssh-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        with:
          host: "ec2-34-213-48-149.us-west-2.compute.amazonaws.com"
          username: "ubuntu"
          password: ""
          script: |
            sudo service apache2 restart
