name: Push to EC2

on: push

permissions: read-all|write-all

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Deploy to EC2
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{secrets.EC2_PEM }}
          REMOTE_HOST: "ec2-16-170-173-195.eu-north-1.compute.amazonaws.com"
          SOURCE: "./"
          REMOTE_USER: "ubuntu"
          TARGET: "/var/www/html"
